name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version environment variable
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t zyange/bank-ver2:${{ env.VERSION }} .
          docker build -t zyange/bank-ver2-login:${{ env.VERSION }} -f ./login/Dockerfile .
          docker build -t zyange/bank-ver2-account:${{ env.VERSION }} -f ./account/Dockerfile .
          docker build -t zyange/bank-ver2-loans:${{ env.VERSION }} -f ./loans/Dockerfile .

      # CD - 도커이미지 푸시
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag zyange/bank-ver2:${{ env.VERSION }} zyange/bank-ver2:latest
          docker tag zyange/bank-ver2-login:${{ env.VERSION }} zyange/bank-ver2-login:latest
          docker tag zyange/bank-ver2-account:${{ env.VERSION }} zyange/bank-ver2-account:latest
          docker tag zyange/bank-ver2-loans:${{ env.VERSION }} zyange/bank-ver2-loans:latest

          docker push zyange/bank-ver2:${{ env.VERSION }}
          docker push zyange/bank-ver2-login:${{ env.VERSION }}
          docker push zyange/bank-ver2-account:${{ env.VERSION }}
          docker push zyange/bank-ver2-loans:${{ env.VERSION }}

          docker push zyange/bank-ver2:latest
          docker push zyange/bank-ver2-login:latest
          docker push zyange/bank-ver2-account:latest
          docker push zyange/bank-ver2-loans:latest
      # Kubernetes 클러스터에 배포
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Configure kubectl to use the cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f mysql-pv-pvc.yaml
          kubectl apply -f mysql-deployment.yaml
          kubectl apply -f mysql-svc.yaml
          kubectl apply -f login-deployment.yaml
          kubectl apply -f login-svc.yaml
          kubectl apply -f app-deployment.yaml
          kubectl apply -f app-svc.yaml
