name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version environment variable
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_ed25519
          chmod 600 id_ed25519

      - name: Create SSH tunnel for Kubernetes API
        run: |
          ssh -vvv -i id_ed25519 -o StrictHostKeyChecking=no -f -N -L 6443:192.168.56.100:6443 root@192.168.55.100

      - name: Build Docker image
        run: |
          docker build -t zyange/bank-ver2:${{ env.VERSION }} .
          docker build -t zyange/bank-ver2-login:${{ env.VERSION }} -f ./login/Dockerfile .
          docker build -t zyange/bank-ver2-account:${{ env.VERSION }} -f ./account/Dockerfile .
          docker build -t zyange/bank-ver2-loans:${{ env.VERSION }} -f ./loans/Dockerfile .

      # CD - 도커이미지 푸시
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag zyange/bank-ver2:${{ env.VERSION }} zyange/bank-ver2:latest
          docker tag zyange/bank-ver2-login:${{ env.VERSION }} zyange/bank-ver2-login:latest
          docker tag zyange/bank-ver2-account:${{ env.VERSION }} zyange/bank-ver2-account:latest
          docker tag zyange/bank-ver2-loans:${{ env.VERSION }} zyange/bank-ver2-loans:latest

          docker push zyange/bank-ver2:${{ env.VERSION }}
          docker push zyange/bank-ver2-login:${{ env.VERSION }}
          docker push zyange/bank-ver2-account:${{ env.VERSION }}
          docker push zyange/bank-ver2-loans:${{ env.VERSION }}

          docker push zyange/bank-ver2:latest
          docker push zyange/bank-ver2-login:latest
          docker push zyange/bank-ver2-account:latest
          docker push zyange/bank-ver2-loans:latest

      # Kubernetes 클러스터에 배포
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.4'

      - name: Configure kubectl to use the cluster
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Check Kubernetes cluster connection
        run: |
          kubectl cluster-info

      - name: Apply mysql kubernetes resources
        run: |
          kubectl apply -f ./yaml/mysql-pv-pvc.yaml
          kubectl apply -f ./yaml/mysql-deployment.yaml
          kubectl apply -f ./yaml/mysql-svc.yaml

      - name: Apply login Kubernetes resources
        run: |
          kubectl apply -f ./yaml/login-deployment.yaml
          kubectl apply -f ./yaml/login-svc.yaml

      - name: Apply app Kubernetes resources
        run: |
          kubectl apply -f ./yaml/app-deployment.yaml
          kubectl apply -f ./yaml/app-svc.yaml
