name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version environment variable
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t zyange/bank-ver2:${{ env.VERSION }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag zyange/bank-ver2:${{ env.VERSION }} zyange/bank-ver2:latest
          docker push zyange/bank-ver2:${{ env.VERSION }}
          docker push zyange/bank-ver2:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Start SSH agent
        run: eval $(ssh-agent -s) && ssh-add ~/.ssh/id_ed25519

      - name: Configure Git
        run: |
          git config --local user.email "zyangee2@gmail.com"
          git config --local user.name "zyangee"

      - name: Commit version update
        run: |
          git add .
          git commit -m "Update version to ${{ env.VERSION }}"
          git push git@github.com:zyangee/bank-kubernetes.git HEAD:main
