name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. 버전 환경 변수 설정
      - name: Set version environment variable
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # 3. SSH 키 설정
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_ed25519
          chmod 600 id_ed25519

      # 4. Bastion Host에 SSH 연결 테스트
      - name: Test SSH connection to Bastion Host
        run: |
          ssh -i id_ed25519 -o StrictHostKeyChecking=no -v root@192.1
